### ISSUE TITLE
The leading indentation is sometimes copied

### ISSUE THREAD

**Issue by dannyconnell** [lumaxis/snippet-copy#17]
Sometimes, when running the "Copy Snippet Without Leading Indentation" it does actually copy the leading indentation.

I'm not exactly sure what is causing this.

However, I've found that if I select all of the leading indentation (by using mouse wheel click and drag) and then tab the code in. And then run the command, it works ok.

I've attached a video which shows the issue happening and then also shows it working properly again after I re-tab in the code:

[Snippet Copy - Leading indentation is sometimes copied.mov.zip](https://github.com/lumaxis/snippet-copy/files/4608661/Snippet.Copy.-.Leading.indentation.is.sometimes.copied.mov.zip)

**Comment by lumaxis** [comment]
Huh, interesting. Yea, I think this is caused by the empty line in the middle which technically has an indentation level of 0, so that's what it detects as the smallest common indentation level.

@dannyconnell Is this something you run into often? I'm wondering how you ended with this in the first place since I would usually expect VS Code to automatically insert whitespace in a situation like that, similar to this:

![CleanShot 2020-05-11 at 22 02 35](https://user-images.githubusercontent.com/406937/81606393-4a2bfa00-93d3-11ea-82d2-cc4b5a4225e9.gif)

I'll think about if I can fix this without breaking any other legitimate cases. Thanks!

**Comment by dannyconnell** [comment]
Yes it does happen quite often. I guess it comes from duplicating a method then clearing it out. See the video:

[Snippet Copy - Duplicate method leaves empty line.mov.zip](https://github.com/lumaxis/snippet-copy/files/4613997/Snippet.Copy.-.Duplicate.method.leaves.empty.line.mov.zip)

**Comment by lumaxis** [comment]
@dannyconnell Finally got around to publishing a fix for this. Can you give 0.2.1 a try and see if that behaves more as you expect? Cheers!
